export const HISTORY_SEARCH_DEBOUNCE_MS = 300;
export const HISTORY_SEARCH_LIMIT = 30;
export const HISTORY_SEARCH_OBSERVER_THRESHOLD = 0.1;
export const HISTORY_SEARCH_OBSERVER_ROOT_MARGIN = "0px 0px 200px 0px";
