# Deploy Workflow Template
# このテンプレートをベースにプロジェクト固有のデプロイワークフローを作成

name: Deploy

on:
  push:
    branches: [main]

env:
  # Discord Webhook URL for notifications
  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Notify deployment start
        if: env.DISCORD_WEBHOOK_URL != ''
        run: |
          curl -X POST "$DISCORD_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d '{
              "embeds": [{
                "title": "🚀 Deployment Started",
                "description": "Deploying to production...",
                "color": 3447003,
                "fields": [
                  {
                    "name": "Repository",
                    "value": "${{ github.repository }}",
                    "inline": true
                  },
                  {
                    "name": "Branch",
                    "value": "${{ github.ref_name }}",
                    "inline": true
                  },
                  {
                    "name": "Commit",
                    "value": "`${{ github.sha }}`",
                    "inline": false
                  },
                  {
                    "name": "Author",
                    "value": "${{ github.actor }}",
                    "inline": true
                  }
                ],
                "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
              }]
            }'

      # Railway は Git 統合で自動デプロイ
      # このステップは Railway のデプロイ完了を待機
      - name: Wait for Railway deployment
        run: |
          echo "⏳ Waiting for Railway to deploy..."
          sleep 30
          echo "✅ Railway deployment should be complete"

      - name: Notify deployment success
        if: success() && env.DISCORD_WEBHOOK_URL != ''
        run: |
          curl -X POST "$DISCORD_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d '{
              "embeds": [{
                "title": "✅ Deployment Successful",
                "description": "Production deployment completed successfully!",
                "color": 3066993,
                "fields": [
                  {
                    "name": "Repository",
                    "value": "${{ github.repository }}",
                    "inline": true
                  },
                  {
                    "name": "Branch",
                    "value": "${{ github.ref_name }}",
                    "inline": true
                  },
                  {
                    "name": "Commit",
                    "value": "`${{ github.sha }}`",
                    "inline": false
                  }
                ],
                "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
              }]
            }'

      - name: Notify deployment failure
        if: failure() && env.DISCORD_WEBHOOK_URL != ''
        run: |
          curl -X POST "$DISCORD_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d '{
              "embeds": [{
                "title": "❌ Deployment Failed",
                "description": "Production deployment failed. Please check the logs.",
                "color": 15158332,
                "fields": [
                  {
                    "name": "Repository",
                    "value": "${{ github.repository }}",
                    "inline": true
                  },
                  {
                    "name": "Branch",
                    "value": "${{ github.ref_name }}",
                    "inline": true
                  },
                  {
                    "name": "Commit",
                    "value": "`${{ github.sha }}`",
                    "inline": false
                  },
                  {
                    "name": "Workflow Run",
                    "value": "[View Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})",
                    "inline": false
                  }
                ],
                "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
              }]
            }'
