# Reusable Workflow Template
# このテンプレートをベースに再利用可能なワークフローを作成

name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: number
        default: 22
      working-directory:
        description: 'Working directory for commands'
        required: false
        type: string
        default: '.'
      run-lint:
        description: 'Whether to run linting'
        required: false
        type: boolean
        default: true
      run-type-check:
        description: 'Whether to run type checking'
        required: false
        type: boolean
        default: true
      run-tests:
        description: 'Whether to run tests'
        required: false
        type: boolean
        default: true
      coverage-threshold:
        description: 'Minimum coverage percentage'
        required: false
        type: number
        default: 80
    secrets:
      NPM_TOKEN:
        description: 'pnpm token for private packages'
        required: false

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        id: cache
        working-directory: ${{ inputs.working-directory }}
        run: pnpm install --frozen-lockfile

  lint:
    name: Lint
    needs: setup
    if: inputs.run-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: pnpm install --frozen-lockfile

      - name: Run linter
        working-directory: ${{ inputs.working-directory }}
        run: pnpm lint

  type-check:
    name: Type Check
    needs: setup
    if: inputs.run-type-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: pnpm install --frozen-lockfile

      - name: Run type check
        working-directory: ${{ inputs.working-directory }}
        run: pnpm tsc --noEmit

  test:
    name: Test
    needs: setup
    if: inputs.run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: pnpm install --frozen-lockfile

      - name: Run tests with coverage
        working-directory: ${{ inputs.working-directory }}
        run: pnpm test --coverage

      - name: Check coverage threshold
        working-directory: ${{ inputs.working-directory }}
        run: |
          if [ -f coverage/coverage-summary.json ]; then
            COVERAGE=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
            echo "Coverage: $COVERAGE%"
            if (( $(echo "$COVERAGE < ${{ inputs.coverage-threshold }}" | bc -l) )); then
              echo "❌ Coverage $COVERAGE% is below threshold ${{ inputs.coverage-threshold }}%"
              exit 1
            fi
            echo "✅ Coverage meets threshold"
          else
            echo "⚠️ Coverage report not found, skipping threshold check"
          fi

  summary:
    name: Summary
    needs: [lint, type-check, test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check results
        run: |
          echo "## Workflow Summary"
          echo ""
          if [ "${{ needs.lint.result }}" == "success" ] || [ "${{ needs.lint.result }}" == "skipped" ]; then
            echo "✅ Lint: ${{ needs.lint.result }}"
          else
            echo "❌ Lint: ${{ needs.lint.result }}"
          fi
          if [ "${{ needs.type-check.result }}" == "success" ] || [ "${{ needs.type-check.result }}" == "skipped" ]; then
            echo "✅ Type Check: ${{ needs.type-check.result }}"
          else
            echo "❌ Type Check: ${{ needs.type-check.result }}"
          fi
          if [ "${{ needs.test.result }}" == "success" ] || [ "${{ needs.test.result }}" == "skipped" ]; then
            echo "✅ Test: ${{ needs.test.result }}"
          else
            echo "❌ Test: ${{ needs.test.result }}"
          fi
