import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "index.ts",
    "core/index.ts",
    "infrastructure/index.ts",
    "infrastructure/auth/index.ts",
    "infrastructure/database/index.ts",
    "infrastructure/ai/apiKeyValidator.ts",
    "types/index.ts",
    "types/auth.ts",
    "types/api-keys.ts",
    "schemas/index.ts",
    "schemas/auth.ts",
    "src/types/index.ts",
    "src/types/skill.ts",
    "src/types/replace.ts",
    "src/types/agent.ts",
    "src/types/agent-execution.ts",
    "src/types/llm/schemas/index.ts",
    "src/types/rag/index.ts",
    "src/types/rag/result.ts",
    "src/agent/index.ts",
    "src/services/history/types.ts",
    "src/services/history/history-service.ts",
    "src/services/logging/types.ts",
    "src/services/logging/conversion-logger.ts",
    "src/slide/index.ts",
    "src/claude-cli/index.ts",
    "utils/index.ts",
    "src/features/chat-history/index.ts",
  ],
  format: ["esm"],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  outDir: "dist",
  target: "es2022",
  treeshake: true,
});
