# PR自動ラベル設定
# ファイルパスに基づいてPRにラベルを自動付与

# アプリケーション
desktop:
  - changed-files:
      - any-glob-to-any-file: 'apps/desktop/**'

web:
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**'

# パッケージ
shared:
  - changed-files:
      - any-glob-to-any-file: 'packages/shared/**'

ui:
  - changed-files:
      - any-glob-to-any-file: 'packages/ui/**'

# ドキュメント
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'

# CI/CD
ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - '*.yml'
          - '*.yaml'

# 設定
config:
  - changed-files:
      - any-glob-to-any-file:
          - '*.json'
          - '*.config.*'
          - 'tsconfig*.json'
          - '.eslintrc*'
          - '.prettierrc*'

# テスト
test:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.test.ts'
          - '**/*.test.tsx'
          - '**/*.spec.ts'
          - '**/__tests__/**'

# データベース
database:
  - changed-files:
      - any-glob-to-any-file:
          - '**/database/**'
          - '**/schema/**'
          - '**/migrations/**'
