# GitHub Actions Workflow Template
# Complete starter template for CI/CD workflow

name: CI/CD Pipeline

# Trigger events configuration
on:
  # Trigger on push to main and develop branches
  push:
    branches:
      - main
      - develop
    paths:
      - "src/**"
      - "tests/**"
      - "package.json"
      - "package-lock.json"
    # Exclude documentation changes
    paths-ignore:
      - "**.md"
      - "docs/**"

  # Trigger on pull requests to main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

  # Manual trigger with input parameters
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      skip-tests:
        description: "Skip tests"
        required: false
        type: boolean
        default: false

  # Scheduled trigger (every day at midnight UTC)
  schedule:
    - cron: "0 0 * * *"

# Global environment variables
env:
  NODE_ENV: production
  CACHE_VERSION: v1

# Default settings for all run steps
defaults:
  run:
    shell: bash

# Concurrency control - cancel in-progress runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Default permissions (read-only)
permissions:
  contents: read

jobs:
  # ============================================
  # Job 1: Lint and Code Quality
  # ============================================
  lint:
    name: Lint and Code Quality
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm ci

      - name: Run linter
        run: pnpm run lint

      - name: Check formatting
        run: pnpm run format:check

      - name: Type check
        run: pnpm run type-check

  # ============================================
  # Job 2: Test with Matrix
  # ============================================
  test:
    name: Test on ${{ matrix.os }} with Node ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      (github.event.inputs.skip-tests != 'true' || github.event.inputs.skip-tests == '')

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [16, 18, 20]
        exclude:
          - os: macos-latest
            node: 16
        include:
          - os: ubuntu-latest
            node: 20
            coverage: true

    # Service containers
    # SQLite/Tursoの場合はサービスコンテナ不要、環境変数のみで接続
    # services:
    #   redis:
    #     image: redis:7
    #     options: >-
    #       --health-cmd "redis-cli ping"
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #     ports:
    #       - 6379:6379

    env:
      TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
      TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
      # REDIS_URL: redis://localhost:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm ci

      - name: Run tests
        run: pnpm test
        timeout-minutes: 10

      - name: Generate coverage report
        if: matrix.coverage
        run: pnpm run test:coverage

      - name: Upload coverage to Codecov
        if: matrix.coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          flags: unittests
          name: coverage-${{ matrix.os }}-${{ matrix.node }}

  # ============================================
  # Job 3: Build
  # ============================================
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [lint, test]
    permissions:
      contents: read

    outputs:
      version: ${{ steps.package-version.outputs.version }}
      artifact-id: ${{ steps.upload.outputs.artifact-id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Get package version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            dist
            .next/cache
          key: ${{ runner.os }}-build-${{ env.CACHE_VERSION }}-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_VERSION }}-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-build-${{ env.CACHE_VERSION }}-

      - name: Install dependencies
        run: pnpm ci

      - name: Build application
        run: pnpm run build
        env:
          NODE_ENV: production

      - name: Upload build artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}
          path: |
            dist/
            .next/
          retention-days: 7
          if-no-files-found: error

  # ============================================
  # Job 4: Security Scan
  # ============================================
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"

      - name: pnpm audit
        run: pnpm audit --audit-level=moderate
        continue-on-error: true

  # ============================================
  # Job 5: Deploy to Staging
  # ============================================
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [build, security]
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/develop'

    environment:
      name: staging
      url: https://staging.example.com

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}
          path: dist/

      - name: Deploy to staging
        env:
          DEPLOY_TOKEN: ${{ secrets.STAGING_DEPLOY_TOKEN }}
          DEPLOY_URL: ${{ secrets.STAGING_DEPLOY_URL }}
        run: |
          echo "Deploying to staging environment..."
          # Add your deployment script here
          # ./scripts/deploy.sh staging

      - name: Run smoke tests
        run: |
          echo "Running smoke tests..."
          # Add smoke test commands
          # pnpm run test:smoke

  # ============================================
  # Job 6: Deploy to Production
  # ============================================
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build, security]
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' ||
      (github.event_name == 'workflow_dispatch' &&
       github.event.inputs.environment == 'production')

    environment:
      name: production
      url: https://example.com

    permissions:
      contents: read
      deployments: write

    concurrency:
      group: production-deploy
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}
          path: dist/

      - name: Deploy to production
        env:
          DEPLOY_TOKEN: ${{ secrets.PRODUCTION_DEPLOY_TOKEN }}
          DEPLOY_URL: ${{ secrets.PRODUCTION_DEPLOY_URL }}
        run: |
          echo "Deploying to production environment..."
          echo "Version: ${{ needs.build.outputs.version }}"
          # Add your deployment script here
          # ./scripts/deploy.sh production

      - name: Create deployment tag
        if: success()
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "deploy-$(date +%Y%m%d-%H%M%S)" -m "Production deployment"
          git push origin --tags

      - name: Run smoke tests
        run: |
          echo "Running production smoke tests..."
          # Add smoke test commands
          # pnpm run test:smoke:production

  # ============================================
  # Job 7: Notification
  # ============================================
  notify:
    name: Send Notification
    runs-on: ubuntu-latest
    needs: [deploy-staging, deploy-production]
    if: always()

    steps:
      - name: Notify on success
        if: |
          needs.deploy-staging.result == 'success' ||
          needs.deploy-production.result == 'success'
        run: |
          echo "Deployment succeeded!"
          # Add notification logic (Slack, Discord, etc.)

      - name: Notify on failure
        if: |
          needs.deploy-staging.result == 'failure' ||
          needs.deploy-production.result == 'failure'
        run: |
          echo "Deployment failed!"
          # Add failure notification logic

  # ============================================
  # Job 8: Cleanup
  # ============================================
  cleanup:
    name: Cleanup Artifacts
    runs-on: ubuntu-latest
    needs: [deploy-staging, deploy-production]
    if: always()

    steps:
      - name: Delete old artifacts
        uses: actions/github-script@v7
        with:
          script: |
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const oldArtifacts = artifacts.data.artifacts.filter(artifact => {
              const daysOld = (Date.now() - new Date(artifact.created_at)) / (1000 * 60 * 60 * 24);
              return daysOld > 7;
            });

            for (const artifact of oldArtifacts) {
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id,
              });
            }
