# OIDC Workflow Examples

## AWS OIDC Authentication

### Basic AWS Deployment
```yaml
name: Deploy to AWS
on:
  push:
    branches: [main]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GitHubActionsRole
          aws-region: us-east-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://my-bucket/ --delete
```

### Multi-Region AWS Deployment
```yaml
name: Multi-Region Deploy
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region:
          - us-east-1
          - us-west-2
          - eu-west-1
          - ap-northeast-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GitHubActionsRole
          aws-region: ${{ matrix.region }}
          role-session-name: GitHubActions-${{ github.run_id }}-${{ matrix.region }}

      - name: Deploy to Region
        run: |
          echo "Deploying to ${{ matrix.region }}"
          aws s3 sync ./dist s3://my-bucket-${{ matrix.region }}/ --delete
```

### AWS with Environment Protection
```yaml
name: Protected AWS Deploy
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (Staging)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_STAGING }}
          aws-region: us-east-1

      - name: Deploy to Staging
        run: ./deploy-staging.sh

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: production
      url: https://example.com
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (Production)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_PRODUCTION }}
          aws-region: us-east-1

      - name: Deploy to Production
        run: ./deploy-production.sh
```

### AWS ECR Push with OIDC
```yaml
name: Build and Push to ECR
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GitHubActionsECRRole
          aws-region: us-east-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: my-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
```

---

## GCP OIDC Authentication

### Basic GCP Deployment
```yaml
name: Deploy to GCP
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions@my-project.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Verify Identity
        run: gcloud auth list

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-service \
            --image gcr.io/my-project/my-image:latest \
            --region us-central1 \
            --platform managed
```

### GCP with Multiple Environments
```yaml
name: GCP Multi-Environment
on:
  push:
    branches: [main, develop]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: staging
            project: my-project-staging
            region: us-central1
          - environment: production
            project: my-project-prod
            region: us-east1
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-service-${{ matrix.environment }} \
            --image gcr.io/${{ matrix.project }}/my-image:${{ github.sha }} \
            --region ${{ matrix.region }} \
            --project ${{ matrix.project }}
```

### GCP with Access Token
```yaml
name: GCP API Access
on: push

permissions:
  id-token: write
  contents: read

jobs:
  api-call:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate and Get Token
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions@my-project.iam.gserviceaccount.com'

      - name: Call GCP API
        run: |
          curl -H "Authorization: Bearer ${{ steps.auth.outputs.access_token }}" \
            https://storage.googleapis.com/storage/v1/b/my-bucket/o
```

### GCP Artifact Registry Push
```yaml
name: Push to Artifact Registry
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Docker for GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push
        run: |
          IMAGE=us-central1-docker.pkg.dev/my-project/my-repo/my-image:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE
```

---

## Azure OIDC Authentication

### Basic Azure Deployment
```yaml
name: Deploy to Azure
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify Azure Identity
        run: az account show

      - name: Deploy to App Service
        run: |
          az webapp deployment source config-zip \
            --resource-group my-rg \
            --name my-webapp \
            --src ./deploy.zip
```

### Azure with Environment Protection
```yaml
name: Azure Protected Deploy
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (Staging)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Staging
        run: ./deploy-staging.sh

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: production
      url: https://example.azurewebsites.net
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (Production)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_PROD }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_PROD }}

      - name: Deploy to Production
        run: ./deploy-production.sh
```

### Azure Container Registry
```yaml
name: Push to ACR
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name myregistry

      - name: Build and Push
        run: |
          docker build -t myregistry.azurecr.io/my-image:${{ github.sha }} .
          docker push myregistry.azurecr.io/my-image:${{ github.sha }}
```

### Azure with Multiple Subscriptions
```yaml
name: Multi-Subscription Deploy
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - name: staging
            subscription: sub-staging-id
          - name: production
            subscription: sub-production-id
    environment: ${{ matrix.environment.name }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ matrix.environment.subscription }}

      - name: Deploy
        run: ./deploy.sh ${{ matrix.environment.name }}
```

---

## HashiCorp Vault OIDC

### Basic Vault Integration
```yaml
name: Vault Secret Access
on: push

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Import Secrets from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault.example.com
          method: jwt
          role: github-actions
          jwtGithubAudience: https://github.com/octo-org
          secrets: |
            secret/data/production/db password | DB_PASSWORD ;
            secret/data/production/api key | API_KEY ;
            secret/data/production/redis url | REDIS_URL

      - name: Use Secrets
        run: |
          echo "Database configured"
          ./deploy.sh
        env:
          DB_PASS: ${{ env.DB_PASSWORD }}
          API: ${{ env.API_KEY }}
          REDIS: ${{ env.REDIS_URL }}
```

### Vault with Dynamic Secrets
```yaml
name: Vault Dynamic Secrets
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Dynamic Database Credentials
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault.example.com
          method: jwt
          role: github-actions
          secrets: |
            database/creds/readonly username | DB_USER ;
            database/creds/readonly password | DB_PASS

      - name: Access Database
        run: |
          psql -h db.example.com -U $DB_USER -d mydb -c "SELECT version();"
        env:
          PGPASSWORD: ${{ env.DB_PASS }}
          DB_USER: ${{ env.DB_USER }}
```

### Vault with Environment-Specific Paths
```yaml
name: Vault Multi-Environment
on:
  push:
    branches: [main, develop]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging, production]
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Import Secrets from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault.example.com
          method: jwt
          role: github-actions-${{ matrix.environment }}
          secrets: |
            secret/data/${{ matrix.environment }}/db password | DB_PASSWORD ;
            secret/data/${{ matrix.environment }}/api key | API_KEY

      - name: Deploy
        run: ./deploy.sh
```

---

## Multi-Cloud OIDC

### AWS + GCP Deployment
```yaml
name: Multi-Cloud Deploy
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GitHubActionsRole
          aws-region: us-east-1

      - name: Deploy to AWS
        run: ./deploy-aws.sh

  deploy-gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Deploy to GCP
        run: ./deploy-gcp.sh
```

### AWS + Azure + GCP
```yaml
name: All-Cloud Deploy
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cloud:
          - name: aws
            region: us-east-1
          - name: gcp
            region: us-central1
          - name: azure
            region: eastus
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to ${{ matrix.cloud.name }}
        run: ./deploy-${{ matrix.cloud.name }}.sh ${{ matrix.cloud.region }}
```

---

## Conditional OIDC Access

### Branch-Based Access
```yaml
name: Branch-Protected Deploy
on:
  push:
    branches: [main, 'release/*']

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (Main Branch)
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/MainBranchRole
          aws-region: us-east-1

      - name: Configure AWS (Release Branch)
        if: startsWith(github.ref, 'refs/heads/release/')
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/ReleaseBranchRole
          aws-region: us-east-1

      - name: Deploy
        run: ./deploy.sh
```

### Environment-Based OIDC
```yaml
name: Environment OIDC
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        type: choice
        options:
          - staging
          - production

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets[format('AWS_ROLE_{0}', github.event.inputs.environment)] }}
          aws-region: us-east-1

      - name: Deploy
        run: ./deploy.sh ${{ github.event.inputs.environment }}
```

---

## Best Practices Examples

### Minimal Permissions
```yaml
name: Minimal Permissions
on: push

permissions:
  id-token: write  # Only what's needed for OIDC
  contents: read   # Only read access to code

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/LimitedAccessRole
          aws-region: us-east-1
          role-duration-seconds: 900  # 15 minutes only

      - name: Deploy
        run: ./deploy.sh
```

### Session Tagging and Monitoring
```yaml
name: Auditable Deploy
on: push

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS with Tags
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GitHubActionsRole
          role-session-name: GHA-${{ github.repository }}-${{ github.run_id }}
          aws-region: us-east-1

      - name: Log Deployment
        run: |
          echo "::notice::Deployment by ${{ github.actor }}"
          echo "::notice::Commit: ${{ github.sha }}"
          echo "::notice::Session: GHA-${{ github.repository }}-${{ github.run_id }}"

      - name: Deploy
        run: ./deploy.sh
```
