import type {
  StoreBoundaryMatrixItem,
  StoreSelectorPolicy,
  StoreSliceInventoryItem,
} from "./types";

export const STORE_PERSISTED_KEYS_BASELINE = [
  "currentView",
  "selectedFile",
  "expandedFolders",
  "userProfile",
  "autoSyncEnabled",
  "windowSize",
  "permissionHistory",
] as const;

export const STORE_SLICE_INVENTORY_BASELINE = [
  {
    sliceName: "NavigationSlice",
    state: ["currentView", "viewHistory", "currentSkillName"],
    actions: ["setCurrentView", "goBack", "canGoBack", "setCurrentSkillName"],
    selectors: ["useCurrentView"],
    persistence: {
      strategy: "partial-persisted",
      keys: ["currentView"],
    },
    ownerView: ["AppDock", "App.tsx"],
    filePath: "apps/desktop/src/renderer/store/slices/navigationSlice.ts",
  },
  {
    sliceName: "EditorSlice",
    state: [
      "selectedFile",
      "fileTree",
      "expandedFolders",
      "editorContent",
      "hasUnsavedChanges",
    ],
    actions: [
      "setSelectedFile",
      "setFileTree",
      "toggleFolder",
      "setExpandedFolders",
      "setEditorContent",
      "setHasUnsavedChanges",
      "markAsSaved",
    ],
    selectors: ["useSelectedFile", "useFileTree", "useExpandedFolders"],
    persistence: {
      strategy: "partial-persisted",
      keys: ["selectedFile", "expandedFolders"],
    },
    ownerView: ["EditorView"],
    filePath: "apps/desktop/src/renderer/store/slices/editorSlice.ts",
  },
  {
    sliceName: "ChatSlice",
    state: [
      "chatMessages",
      "chatInput",
      "isSending",
      "isStreaming",
      "systemPrompt",
    ],
    actions: [
      "sendMessage",
      "addMessage",
      "clearMessages",
      "setChatInput",
      "startStreaming",
      "endStreaming",
    ],
    selectors: ["useChatMessages", "useIsSending"],
    persistence: {
      strategy: "non-persisted",
      keys: [],
    },
    ownerView: ["ChatView"],
    filePath: "apps/desktop/src/renderer/store/slices/chatSlice.ts",
  },
  {
    sliceName: "GraphSlice",
    state: ["graphNodes", "graphLinks", "isAnimating", "selectedNodeId"],
    actions: [
      "setGraphData",
      "setIsAnimating",
      "setSelectedNode",
      "updateNodePosition",
      "clearGraph",
    ],
    selectors: ["useGraphNodes", "useGraphLinks", "useIsAnimating"],
    persistence: {
      strategy: "non-persisted",
      keys: [],
    },
    ownerView: ["GraphView"],
    filePath: "apps/desktop/src/renderer/store/slices/graphSlice.ts",
  },
  {
    sliceName: "SettingsSlice",
    state: [
      "userProfile",
      "apiKey",
      "autoSyncEnabled",
      "themeMode",
      "resolvedTheme",
    ],
    actions: [
      "setUserProfile",
      "updateUserProfile",
      "setApiKey",
      "setAutoSyncEnabled",
      "setThemeMode",
      "setResolvedTheme",
      "initializeTheme",
    ],
    selectors: [
      "useThemeMode",
      "useResolvedTheme",
      "useSetThemeMode",
      "useSetResolvedTheme",
      "useInitializeTheme",
    ],
    persistence: {
      strategy: "partial-persisted",
      keys: ["userProfile", "autoSyncEnabled"],
    },
    ownerView: ["SettingsView"],
    filePath: "apps/desktop/src/renderer/store/slices/settingsSlice.ts",
  },
  {
    sliceName: "UISlice",
    state: [
      "dynamicIsland",
      "mobileDrawerOpen",
      "windowSize",
      "responsiveMode",
      "isSystemPromptPanelExpanded",
    ],
    actions: [
      "showDynamicIsland",
      "hideDynamicIsland",
      "setMobileDrawerOpen",
      "toggleMobileDrawer",
      "setWindowSize",
    ],
    selectors: ["useDynamicIsland", "useResponsiveMode", "useMobileDrawerOpen"],
    persistence: {
      strategy: "partial-persisted",
      keys: ["windowSize"],
    },
    ownerView: ["App.tsx"],
    filePath: "apps/desktop/src/renderer/store/slices/uiSlice.ts",
  },
  {
    sliceName: "DashboardSlice",
    state: ["dashboardStats", "activityFeed", "isLoading"],
    actions: [
      "setDashboardStats",
      "setActivityFeed",
      "addActivity",
      "setIsLoading",
    ],
    selectors: ["useDashboardStats", "useActivityFeed"],
    persistence: {
      strategy: "non-persisted",
      keys: [],
    },
    ownerView: ["DashboardView"],
    filePath: "apps/desktop/src/renderer/store/slices/dashboardSlice.ts",
  },
  {
    sliceName: "AuthSlice",
    state: [
      "isAuthenticated",
      "authUser",
      "sessionExpiresAt",
      "profile",
      "linkedProviders",
      "isOffline",
      "authError",
    ],
    actions: [
      "login",
      "logout",
      "initializeAuth",
      "refreshSession",
      "fetchProfile",
      "fetchLinkedProviders",
      "clearAuth",
    ],
    selectors: [
      "useIsAuthenticated",
      "useAuthUser",
      "useSessionExpiresAt",
      "useUserProfile",
      "useLinkedProviders",
      "useAuthLoading",
      "useAuthError",
      "useIsOffline",
    ],
    persistence: {
      strategy: "non-persisted",
      keys: [],
    },
    ownerView: ["AuthView", "SettingsView", "App.tsx"],
    filePath: "apps/desktop/src/renderer/store/slices/authSlice.ts",
  },
  {
    sliceName: "AuthModeSlice",
    state: [
      "mode",
      "status",
      "isLoading",
      "error",
      "isConfirmDialogOpen",
      "pendingMode",
    ],
    actions: [
      "fetchMode",
      "setMode",
      "fetchStatus",
      "validate",
      "openConfirmDialog",
      "closeConfirmDialog",
      "confirmModeChange",
      "clearError",
      "resetAuthMode",
      "initializeAuthMode",
    ],
    selectors: [
      "useAuthMode",
      "useAuthModeStatus",
      "useAuthModeLoading",
      "useAuthModeError",
      "useIsAuthModeValid",
      "useSetAuthMode",
      "useInitializeAuthMode",
      "useFetchAuthMode",
      "useFetchAuthModeStatus",
      "useValidateAuthMode",
      "useOpenConfirmDialog",
      "useCloseConfirmDialog",
      "useConfirmModeChange",
      "useClearAuthModeError",
      "useResetAuthMode",
    ],
    persistence: {
      strategy: "non-persisted",
      keys: [],
    },
    ownerView: ["SettingsView"],
    filePath: "apps/desktop/src/renderer/store/slices/authModeSlice.ts",
  },
  {
    sliceName: "WorkspaceSlice",
    state: [
      "workspace",
      "folderFileTrees",
      "workspaceIsLoading",
      "workspaceError",
    ],
    actions: [
      "loadWorkspace",
      "saveWorkspace",
      "addFolder",
      "removeFolder",
      "toggleFolderExpansion",
      "toggleSubfolder",
      "setWorkspaceSelectedFile",
    ],
    selectors: [
      "useWorkspace",
      "useFolderFileTrees",
      "useWorkspaceLoading",
      "useWorkspaceError",
      "useLoadWorkspace",
      "useSaveWorkspace",
      "useAddFolder",
      "useRemoveFolder",
      "useToggleFolderExpansion",
      "useToggleSubfolder",
      "useSetWorkspaceSelectedFile",
    ],
    persistence: {
      strategy: "non-persisted",
      keys: [],
    },
    ownerView: ["EditorView"],
    filePath: "apps/desktop/src/renderer/store/slices/workspaceSlice.ts",
  },
  {
    sliceName: "FileSelectionSlice",
    state: [
      "selectedFiles",
      "filterCategory",
      "isDragging",
      "isLoading",
      "error",
      "lastSelectedId",
    ],
    actions: [
      "addFiles",
      "removeFile",
      "removeFiles",
      "clearFiles",
      "reorderFile",
      "setFilterCategory",
      "setIsDragging",
      "setIsLoading",
      "setError",
      "clearError",
      "resetFileSelection",
    ],
    selectors: [
      "useSelectedFiles",
      "useHasSelectedFiles",
      "useFileFilterCategory",
      "useFileSelectionIsDragging",
      "useFileSelectionIsLoading",
      "useFileSelectionError",
      "useLastSelectedId",
      "useAddFiles",
      "useRemoveFile",
      "useRemoveFiles",
      "useClearFiles",
      "useReorderFile",
      "useSetFileFilterCategory",
      "useSetFileSelectionIsDragging",
      "useSetFileSelectionIsLoading",
      "useSetFileSelectionError",
      "useClearFileSelectionError",
      "useResetFileSelection",
    ],
    persistence: {
      strategy: "non-persisted",
      keys: [],
    },
    ownerView: ["EditorView", "AgentExecutionView"],
    filePath: "apps/desktop/src/renderer/store/slices/fileSelectionSlice.ts",
  },
  {
    sliceName: "SystemPromptTemplateSlice",
    state: ["templates"],
    actions: [
      "initializeTemplates",
      "saveTemplate",
      "updateTemplate",
      "deleteTemplate",
      "getTemplateById",
    ],
    selectors: [],
    persistence: {
      strategy: "non-persisted",
      keys: [],
    },
    ownerView: ["SettingsView"],
    filePath:
      "apps/desktop/src/renderer/store/slices/systemPromptTemplateSlice.ts",
  },
  {
    sliceName: "LLMSlice",
    state: [
      "providers",
      "selectedProviderId",
      "selectedModelId",
      "llmIsLoading",
      "llmError",
      "healthStatus",
    ],
    actions: [
      "fetchProviders",
      "selectProvider",
      "selectModel",
      "checkHealth",
      "resetSelection",
      "clearLLMError",
      "setLLMLoading",
      "setLLMError",
      "getSelectedProvider",
      "getSelectedModel",
      "isProviderAvailable",
    ],
    selectors: [
      "useLLMProviders",
      "useSelectedProviderId",
      "useSelectedModelId",
      "useLLMIsLoading",
      "useLLMError",
      "useLLMHealthStatus",
      "useFetchProviders",
      "useSelectProvider",
      "useSelectModel",
      "useCheckLLMHealth",
      "useResetLLMSelection",
      "useClearLLMError",
      "useSetLLMLoading",
      "useSetLLMError",
      "useSelectedLLMProvider",
      "useSelectedLLMModel",
    ],
    persistence: {
      strategy: "non-persisted",
      keys: [],
    },
    ownerView: ["SettingsView", "AgentView"],
    filePath: "apps/desktop/src/renderer/store/slices/llmSlice.ts",
  },
  {
    sliceName: "AgentSlice",
    state: [
      "skills",
      "availableSkills",
      "importedSkillIds",
      "selectedSkill",
      "skillFilter",
      "skillCategory",
      "isImportDialogOpen",
      "executionStatus",
      "executionState",
      "availableSkillsMetadata",
      "importedSkills",
      "selectedSkillName",
      "isExecuting",
      "executionId",
      "skillExecutionStatus",
      "streamingMessages",
      "pendingPermission",
      "skillError",
      "isLoadingSkills",
      "isScanning",
      "isImporting",
      "currentAnalysis",
      "isAnalyzing",
      "isImproving",
    ],
    actions: [
      "setSkills",
      "setAvailableSkills",
      "setImportedSkillIds",
      "selectSkill",
      "setSkillFilter",
      "setSkillCategory",
      "openImportDialog",
      "closeImportDialog",
      "showToast",
      "clearToast",
      "startExecution",
      "stopExecution",
      "fetchSkills",
      "rescanSkills",
      "importSkill",
      "removeSkill",
      "selectSkillByName",
      "executeSkill",
      "abortExecution",
      "respondToSkillPermission",
      "clearSkillError",
      "clearStreamingMessages",
      "analyzeSkill",
      "applySkillImprovements",
      "autoImproveSkill",
      "createSkill",
      "clearAnalysis",
    ],
    selectors: [
      "useAvailableSkillsMetadata",
      "useImportedSkills",
      "useSelectedSkillName",
      "useIsSkillExecuting",
      "useSkillExecutionId",
      "useSkillExecutionStatus",
      "useStreamingMessages",
      "usePendingSkillPermission",
      "useSkillError",
      "useIsLoadingSkills",
      "useIsScanningSkills",
      "useIsImportingSkill",
      "useImportingSkillName",
      "useFetchSkills",
      "useRescanSkills",
      "useImportSkill",
      "useRemoveSkill",
      "useSelectSkillByName",
      "useExecuteSkill",
      "useAbortSkillExecution",
      "useRespondToSkillPermission",
      "useClearSkillError",
      "useClearStreamingMessages",
      "useCurrentAnalysis",
      "useIsAnalyzingSkill",
      "useIsImprovingSkill",
      "useAnalyzeSkill",
      "useApplySkillImprovements",
      "useAutoImproveSkill",
      "useCreateSkill",
      "useClearAnalysis",
      "useSkills",
      "useAvailableSkills",
      "useImportedSkillIds",
      "useSelectedSkill",
      "useSkillFilter",
      "useSkillCategory",
      "useIsImportDialogOpen",
      "useToastMessage",
      "useSelectSkill",
      "useSetSkillFilter",
      "useSetSkillCategory",
      "useOpenImportDialog",
      "useCloseImportDialog",
      "useShowToast",
      "useClearToast",
    ],
    persistence: {
      strategy: "non-persisted",
      keys: [],
    },
    ownerView: [
      "AgentView",
      "SkillCenterView",
      "SkillEditorView",
      "SkillChainBuilder",
      "ScheduleManager",
      "DebugPanel",
      "AnalyticsDashboard",
    ],
    filePath: "apps/desktop/src/renderer/store/slices/agentSlice.ts",
  },
  {
    sliceName: "ChatEditSlice",
    state: [
      "fileContexts",
      "activeContextId",
      "generatedResults",
      "currentResultId",
      "isLoading",
      "isDiffPreviewOpen",
      "error",
      "isDragging",
    ],
    actions: [
      "addFileContext",
      "removeFileContext",
      "clearAllContexts",
      "setActiveContext",
      "setGeneratedResult",
      "approveResult",
      "rejectResult",
      "setCurrentResult",
      "setDiffPreviewOpen",
      "setLoading",
      "setError",
      "setDragging",
      "resetState",
    ],
    selectors: [],
    persistence: {
      strategy: "non-persisted",
      keys: [],
    },
    ownerView: ["workspace-chat-edit"],
    filePath:
      "apps/desktop/src/renderer/features/workspace-chat-edit/store/chatEditSlice.ts",
  },
  {
    sliceName: "PermissionHistorySlice",
    state: ["permissionHistory", "historyFilter"],
    actions: ["addHistoryEntry", "clearHistory", "setHistoryFilter"],
    selectors: [],
    persistence: {
      strategy: "partial-persisted",
      keys: ["permissionHistory"],
    },
    ownerView: ["SettingsView", "AgentExecutionView"],
    filePath:
      "apps/desktop/src/renderer/store/slices/permissionHistorySlice.ts",
  },
] as const satisfies readonly StoreSliceInventoryItem[];

export const STORE_BOUNDARY_MATRIX_BASELINE = [
  {
    domain: "Notification",
    decision: "new",
    target: "notificationSlice",
    rationale:
      "通知履歴と未読数は画面横断で共有されるため独立ドメインとして管理する。",
    handoffTask: "task-056c-notification-history-domain.md",
  },
  {
    domain: "HistorySearch",
    decision: "new",
    target: "historySearchSlice",
    rationale:
      "検索クエリ・結果・統計を一貫管理するため既存Sliceから分離する。",
    handoffTask: "task-056c-notification-history-domain.md",
  },
  {
    domain: "SkillCenter",
    decision: "local-useState",
    target: "SkillCenterView local state",
    rationale:
      "詳細パネル開閉や削除確認は画面局所状態でありStore共有は不要である。",
    handoffTask: "task-056c-notification-history-domain.md",
  },
  {
    domain: "ViewType",
    decision: "extend",
    target: "store/types.ts ViewType union",
    rationale:
      "画面遷移責務は既存 NavigationSlice が担うため型拡張で対応できる。",
    handoffTask: "task-056d-viewtype-routing-nav.md",
  },
  {
    domain: "Workspace",
    decision: "no-change",
    target: "workspaceSlice",
    rationale:
      "既存 workspaceSlice がフォルダとファイル状態の責務を満たしている。",
    handoffTask: "task-056d-viewtype-routing-nav.md",
  },
] as const satisfies readonly StoreBoundaryMatrixItem[];

export const STORE_SELECTOR_POLICY_BASELINE = {
  namingConvention: {
    stateSelectorPattern: "use{State}{Domain}",
    actionSelectorPattern: "use{Verb}{Domain}",
    requireDomainSuffix: true,
  },
  deprecatedCompositeHooks: [
    "useLLMStore",
    "useSkillStore",
    "useAuthModeStore",
  ],
  bannedGenericSelectorNames: ["useError", "useLoading", "useData"],
  requiredDomainSelectors: [
    "useIsAnalyzingSkill",
    "useFetchAuthMode",
    "useFetchProviders",
    "useFetchSkills",
  ],
  notes: [
    "P31対策として合成Hookの新規利用を禁止する。",
    "Store関数を依存配列に入れる場合は個別セレクタ経由のみ許可する。",
    "汎用名よりドメイン接尾辞つきの命名を優先する。",
  ],
} as const satisfies StoreSelectorPolicy;
