name: "Discord Deploy Notification"
description: "Send deployment status to Discord webhook"

inputs:
  webhook_url:
    description: "Discord Webhook URL"
    required: true
  status:
    description: "Deployment status (success/failure)"
    required: true
  service:
    description: "Service name (backend/web)"
    required: true
  error_message:
    description: "Error message (only for failure)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Send Discord Notification
      shell: bash
      env:
        WEBHOOK_URL: ${{ inputs.webhook_url }}
        STATUS: ${{ inputs.status }}
        SERVICE: ${{ inputs.service }}
        ERROR_MESSAGE: ${{ inputs.error_message }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_RUN_ID: ${{ github.run_id }}
      run: |
        # カラーと タイトル設定
        if [ "$STATUS" = "success" ]; then
          COLOR=3066993
          TITLE="✅ Deploy Succeeded"
          DESC="Deployment completed successfully."
        else
          COLOR=15158332
          TITLE="❌ Deploy Failed"
          DESC="Deployment encountered an error."
        fi

        # URL生成
        COMMIT_URL="https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
        RUN_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        SHORT_SHA="${GITHUB_SHA:0:7}"

        # フィールド構築
        FIELDS="[
          {\"name\": \"Service\", \"value\": \"${SERVICE}\", \"inline\": true},
          {\"name\": \"Branch\", \"value\": \"${GITHUB_REF_NAME}\", \"inline\": true},
          {\"name\": \"Commit\", \"value\": \"[${SHORT_SHA}](${COMMIT_URL})\", \"inline\": true},
          {\"name\": \"Author\", \"value\": \"@${GITHUB_ACTOR}\", \"inline\": true}"

        # エラーメッセージがあれば追加
        if [ -n "$ERROR_MESSAGE" ]; then
          FIELDS="${FIELDS},
          {\"name\": \"Error\", \"value\": \"${ERROR_MESSAGE}\", \"inline\": false}"
        fi

        # Workflow リンク追加
        FIELDS="${FIELDS},
          {\"name\": \"Workflow\", \"value\": \"[View Run](${RUN_URL})\", \"inline\": false}
        ]"

        # タイムスタンプ生成
        TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

        # ペイロード構築
        PAYLOAD="{
          \"embeds\": [{
            \"title\": \"${TITLE}\",
            \"description\": \"${DESC}\",
            \"color\": ${COLOR},
            \"fields\": ${FIELDS},
            \"timestamp\": \"${TIMESTAMP}\",
            \"footer\": {\"text\": \"AI Workflow Orchestrator\"}
          }]
        }"

        # 送信
        curl -s -o /dev/null -w "%{http_code}" \
             -H "Content-Type: application/json" \
             -d "$PAYLOAD" \
             "$WEBHOOK_URL" || true

        echo "Discord notification sent (status: $STATUS, service: $SERVICE)"
